CREATE DATABASE cuckoo WITH ENCODING 'UTF8';

\c cuckoo;

CREATE ROLE cuckoo_admin LOGIN ENCRYPTED PASSWORD '6TYCKTOehdCQcu6b0OSyaXZz9NVWAMCsD4BsNQdSTOpdLLEHcC13XQqBQnEboSF';
GRANT CONNECT ON DATABASE cuckoo TO cuckoo_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO cuckoo_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cuckoo_admin;

-- create tables --
CREATE TABLE IF NOT EXISTS stock (
  id TEXT NOT NULL,
  name TEXT NOT NULL,
  industry TEXT,
  found_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS stock_records (
  id TEXT NOT NULL REFERENCES stock(id),
  date  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  highest_price
  lowest_price
  open_price
  close_price
  quantity
);
